[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'make'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo='Yggdroot/indentLine'
hook_add='''
let g:indentLine_char='|'
'''

[[plugins]]
repo='scrooloose/nerdtree'
hook_add='''
    " show dotfile
    let g:NERDTreeShowHidden=1
    map <Space>n :NERDTreeToggle<CR>
'''

[[plugins]]
repo='jistr/vim-nerdtree-tabs'
hook_add='''
    let g:nerdtree_tabs_open_on_console_startup=0
    let g:nerdtree_tabs_open_on_gui_startup=0
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
