[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = ['tex']
hook_add='''
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_FormatDependency_pdf = 'pdf'

let g:Tex_CompileRule_pdf = 'latexmk'

let g:Tex_ViewRule_dvi = 'xdvi'
let g:Tex_ViewRule_pdf = 'evince'
let g:Tex_AutoFolding = 0
'''

[[plugins]]
repo= 'vim-jp/cpp-vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']
hook_add='''
let g:clang_c_options = '-std=c11'
let g:clang_cpp_options = '-std=gnu++11 --pedantic-errors'
'''
[[plugins]]
repo='pdavydov108/vim-lsp-cquery'
on_ft = ['c', 'cpp', 'objc', 'objcpp']
hook_add='''
autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fv :LspCqueryDerived<CR>
autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fc :LspCqueryCallers<CR>
autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fb :LspCqueryBase<CR>
autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fi :LspCqueryVars<CR>
'''
