[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source='''
    if !exists('g:neocomplete#source#omni#input_patterns')
        let g:neocomplete#source#omni#input_patterns = {}
    endif
    let g:neocomplete#source#omni#input_patterns = g:vimtex#re#neocomplete
'''

[[plugins]]
repo= 'vim-jp/cpp-vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo='roxma/nvim-yarp'
on_source = ['vim-hug-neovim-rpc']
depends=['vim-hug-neovim-rpc']
# depends pynvim (pip3 install pynvim)

[[plugins]]
repo='cespare/vim-toml'
on_ft=['toml']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft=['html', 'htm', 'css', 'jsp']
hook_add='''
let g:user_emmet_leader_key='<c-l>'
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
