[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo='roxma/nvim-yarp'
depends=['vim-hug-neovim-rpc']
# depends pynvim (pip3 install pynvim)

[[plugins]]
repo='roxma/vim-hug-neovim-rpc'

[[plugins]]
repo='Shougo/deoplete.nvim'
depends=['nvim-yarp', 'vim-hug-neovim-rpc']
hook_add='''
    let g:deoplete#enable_at_startup = 0
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'make'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo='Yggdroot/indentLine'
hook_add='''
let g:indentLine_char='|'
'''

[[plugins]]
repo='scrooloose/nerdtree'
hook_add='''
    " show dotfile
    let g:NERDTreeShowHidden=1
    map <Space>n :NERDTreeToggle<CR>
'''

[[plugins]]
repo='jistr/vim-nerdtree-tabs'
hook_add='''
    let g:nerdtree_tabs_open_on_console_startup=0
    let g:nerdtree_tabs_open_on_gui_startup=0
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
